CREATE TABLE Producto (Id int IDENTITY(1, 1) NOT NULL, Nombre varchar(255) NOT NULL UNIQUE, Descripcion varchar(255) NULL, UnidadMedidaId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Usuario (Id int IDENTITY(1, 1) NOT NULL, Nombre varchar(255) NOT NULL UNIQUE, RolId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Rol (Id int IDENTITY(1, 1) NOT NULL, Nombre varchar(255) NOT NULL UNIQUE, PRIMARY KEY (Id));
CREATE TABLE Ventas (Id int IDENTITY(1, 1) NOT NULL, Fecha date NOT NULL, Importe decimal(19,2) NOT NULL, Cantidad int NOT NULL, Observacion varchar(255) NULL, UsuarioId int NOT NULL, InvertarioProductosId int NOT NULL, TrabajadorPersonaId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE InvertarioProductos (Id int IDENTITY(1, 1) NOT NULL, ProductoId int NOT NULL, CostoUnitario decimal(19,2) NOT NULL, Existencia int NOT NULL, PRIMARY KEY (Id), CONSTRAINT UniqueInventario UNIQUE (ProductoId, CostoUnitario));
CREATE TABLE UnidadMedida (Id int IDENTITY(1, 1) NOT NULL, Unidad varchar(255) NOT NULL UNIQUE, Siglas varchar(5) NOT NULL UNIQUE, PRIMARY KEY (Id));
CREATE TABLE EntradaProductos (Id int IDENTITY(1, 1) NOT NULL, Fecha date NOT NULL, Importe decimal(19,2) NOT NULL, Cantidad int NOT NULL, Observacion varchar(255) NULL, UsuarioId int NOT NULL, InvertarioProductosId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Material (Id int IDENTITY(1, 1) NOT NULL, Nombre varchar(255) NOT NULL UNIQUE, Descripcion varchar(255) NULL, UnidadMedidaId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE InvertarioMateriales (Id int IDENTITY(1, 1) NOT NULL, MaterialId int NOT NULL, Precio decimal(19,2) NOT NULL, Existencia int NOT NULL, Descripcion varchar(255) NULL, PRIMARY KEY (Id), CONSTRAINT UniqueMaterial UNIQUE (MaterialId, Precio));
CREATE TABLE CompraMateriales (Id int IDENTITY(1, 1) NOT NULL, Fecha date NOT NULL, Importe decimal(19,2) NOT NULL, Cantidad int NOT NULL, Observacion varchar(255) NULL, UsuarioId int NOT NULL, InvertarioMaterialesId int NOT NULL, ProveedorPersonaId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE SalidaMateriales (Id int IDENTITY(1, 1) NOT NULL, Fecha date NOT NULL, Cantidad int NOT NULL, Observacion varchar(255) NULL, UsuarioId int NOT NULL, InvertarioMaterialesId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE OtrosGastos (Id int IDENTITY(1, 1) NOT NULL, Fecha date NOT NULL, Importe decimal(19,2) NOT NULL, UsuarioId int NOT NULL, ConceptoGastoId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE ConceptoGasto (Id int IDENTITY(1, 1) NOT NULL, Nombre varchar(255) NOT NULL, Descripcion varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE Trabajador (PersonaId int NOT NULL, AreaTrabajoId int NOT NULL, PRIMARY KEY (PersonaId));
CREATE TABLE Proveedor (PersonaId int NOT NULL, Email varchar(255) NULL, PRIMARY KEY (PersonaId));
CREATE TABLE Persona (Id int IDENTITY(1, 1) NOT NULL, NombreApellidos varchar(255) NOT NULL, Direccion varchar(255) NULL, Telefono varchar(255) NULL, PRIMARY KEY (Id));
CREATE TABLE Proveedor_Material (ProveedorPersonaId int NOT NULL, MaterialId int NOT NULL, PRIMARY KEY (ProveedorPersonaId, MaterialId));
CREATE TABLE Salario (Id int IDENTITY(1, 1) NOT NULL, Fecha date NOT NULL, Importe decimal(19,2) NOT NULL, TrabajadorPersonaId int NOT NULL, PRIMARY KEY (Id));
CREATE TABLE AreaTrabajo (Id int IDENTITY(1, 1) NOT NULL, Nombre varchar(255) NOT NULL UNIQUE, PRIMARY KEY (Id));
CREATE TABLE Producto_Material (ProductoId int NOT NULL, MaterialId int NOT NULL, Cantidad int NOT NULL, PRIMARY KEY (ProductoId, MaterialId));
ALTER TABLE Usuario ADD CONSTRAINT FKUsuario36525 FOREIGN KEY (RolId) REFERENCES Rol (Id);
ALTER TABLE InvertarioProductos ADD CONSTRAINT FKInvertario944054 FOREIGN KEY (ProductoId) REFERENCES Producto (Id);
ALTER TABLE Producto ADD CONSTRAINT FKProducto766971 FOREIGN KEY (UnidadMedidaId) REFERENCES UnidadMedida (Id);
ALTER TABLE Ventas ADD CONSTRAINT FKVentas170181 FOREIGN KEY (UsuarioId) REFERENCES Usuario (Id);
ALTER TABLE EntradaProductos ADD CONSTRAINT FKEntradaPro774223 FOREIGN KEY (UsuarioId) REFERENCES Usuario (Id);
ALTER TABLE Material ADD CONSTRAINT FKMaterial596249 FOREIGN KEY (UnidadMedidaId) REFERENCES UnidadMedida (Id);
ALTER TABLE InvertarioMateriales ADD CONSTRAINT FKInvertario965581 FOREIGN KEY (MaterialId) REFERENCES Material (Id);
ALTER TABLE CompraMateriales ADD CONSTRAINT FKCompraMate522193 FOREIGN KEY (UsuarioId) REFERENCES Usuario (Id);
ALTER TABLE SalidaMateriales ADD CONSTRAINT FKSalidaMate199871 FOREIGN KEY (UsuarioId) REFERENCES Usuario (Id);
ALTER TABLE EntradaProductos ADD CONSTRAINT FKEntradaPro653931 FOREIGN KEY (InvertarioProductosId) REFERENCES InvertarioProductos (Id);
ALTER TABLE Ventas ADD CONSTRAINT FKVentas49889 FOREIGN KEY (InvertarioProductosId) REFERENCES InvertarioProductos (Id);
ALTER TABLE CompraMateriales ADD CONSTRAINT FKCompraMate219076 FOREIGN KEY (InvertarioMaterialesId) REFERENCES InvertarioMateriales (Id);
ALTER TABLE SalidaMateriales ADD CONSTRAINT FKSalidaMate497011 FOREIGN KEY (InvertarioMaterialesId) REFERENCES InvertarioMateriales (Id);
ALTER TABLE OtrosGastos ADD CONSTRAINT FKOtrosGasto598550 FOREIGN KEY (UsuarioId) REFERENCES Usuario (Id);
ALTER TABLE OtrosGastos ADD CONSTRAINT FKOtrosGasto791932 FOREIGN KEY (ConceptoGastoId) REFERENCES ConceptoGasto (Id);
ALTER TABLE Proveedor ADD CONSTRAINT FKProveedor135413 FOREIGN KEY (PersonaId) REFERENCES Persona (Id);
ALTER TABLE Trabajador ADD CONSTRAINT FKTrabajador596797 FOREIGN KEY (PersonaId) REFERENCES Persona (Id);
ALTER TABLE CompraMateriales ADD CONSTRAINT FKCompraMate814930 FOREIGN KEY (ProveedorPersonaId) REFERENCES Proveedor (PersonaId);
ALTER TABLE Proveedor_Material ADD CONSTRAINT FKProveedor_585764 FOREIGN KEY (ProveedorPersonaId) REFERENCES Proveedor (PersonaId);
ALTER TABLE Proveedor_Material ADD CONSTRAINT FKProveedor_681035 FOREIGN KEY (MaterialId) REFERENCES Material (Id);
ALTER TABLE Salario ADD CONSTRAINT FKSalario6470 FOREIGN KEY (TrabajadorPersonaId) REFERENCES Trabajador (PersonaId);
ALTER TABLE Trabajador ADD CONSTRAINT FKTrabajador28344 FOREIGN KEY (AreaTrabajoId) REFERENCES AreaTrabajo (Id);
ALTER TABLE Ventas ADD CONSTRAINT FKVentas365277 FOREIGN KEY (TrabajadorPersonaId) REFERENCES Trabajador (PersonaId);
ALTER TABLE Producto_Material ADD CONSTRAINT FKProducto_M71108 FOREIGN KEY (ProductoId) REFERENCES Producto (Id);
ALTER TABLE Producto_Material ADD CONSTRAINT FKProducto_M10400 FOREIGN KEY (MaterialId) REFERENCES Material (Id);
