//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public Color()
        {
            this.CompraMateriales = new HashSet<CompraMateriales>();
            this.EntradaProductos = new HashSet<EntradaProductos>();
            this.InvertarioMateriales = new HashSet<InvertarioMateriales>();
            this.InvertarioProductos = new HashSet<InvertarioProductos>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "{0} es obligatorio")]
        [Remote("CheckNombre", "Color", AdditionalFields = "Id", ErrorMessage = "Ya existe este Concepto de Costo")]
        public string Nombre { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
    
        public virtual ICollection<CompraMateriales> CompraMateriales { get; set; }
        public virtual ICollection<EntradaProductos> EntradaProductos { get; set; }
        public virtual ICollection<InvertarioMateriales> InvertarioMateriales { get; set; }
        public virtual ICollection<InvertarioProductos> InvertarioProductos { get; set; }
        public string DescricionCompleta
        {
            get
            {
                var d = Nombre;
                if (Descripcion != null && Descripcion != "")
                {
                    d += " (" + Descripcion + ")";
                }
                return d;
            }
        }
    }
}
