//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoGasto
    {
        public ConceptoGasto()
        {
            this.OtrosGastos = new HashSet<OtrosGastos>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "{0} es obligatorio")]
        [Remote("CheckNombre", "ConceptoGasto", AdditionalFields = "Id", ErrorMessage = "Ya existe este Concepto de Gasto")]
        public string Nombre { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
    
        public virtual ICollection<OtrosGastos> OtrosGastos { get; set; }
    }
}
