//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptoCosto
    {
        public ConceptoCosto()
        {
            this.Salario_CostoProduccion = new HashSet<Salario_CostoProduccion>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "{0} es obligatorio")]
        [Remote("CheckNombre", "ConceptoCosto", AdditionalFields = "Id", ErrorMessage = "Ya existe este Concepto de Pago")]
        public string Nombre { get; set; }
    
        public virtual ICollection<Salario_CostoProduccion> Salario_CostoProduccion { get; set; }
    }
}
