//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradaProductos
    {
        public EntradaProductos()
        {
            this.Salario_CostoProduccion = new HashSet<Salario_CostoProduccion>();
            this.ProductoConfeccionadoInventarioMaterial = new HashSet<ProductoConfeccionadoInventarioMaterial>();
        }
    
        public int Id { get; set; }
        [DataType(DataType.Date, ErrorMessage = "{0} debe ser una fecha")]
        [Required(ErrorMessage = "{0} es obligatorio")]
        public System.DateTime Fecha { get; set; }
        public int ProductoId { get; set; }
        public int ColorId { get; set; }
        [DataType(DataType.Currency, ErrorMessage = "Debe ser en formato de moneda")]
        [Required(ErrorMessage = "{0} es obligatorio")]
        [RegularExpression(@"\d*.\d{2}", ErrorMessageResourceName = "DecimalInvalidMessage", ErrorMessageResourceType = typeof(Resources.ResourceGlobal))]
        [Display(Name = "Importe Total")]
        public decimal Importe { get; set; }
        [Required(ErrorMessage = "{0} es obligatorio")]
        [RegularExpression(@"\d*", ErrorMessageResourceName = "IntInvalidMessage", ErrorMessageResourceType = typeof(Resources.ResourceGlobal))]
        public int Cantidad { get; set; }

        [Display(Name = "Observación")]
        public string Observacion { get; set; }

        [Display(Name = "Usuario")]
        public string UsuarioId { get; set; }
        public bool Confeccionado { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual ICollection<Salario_CostoProduccion> Salario_CostoProduccion { get; set; }
        public virtual ICollection<ProductoConfeccionadoInventarioMaterial> ProductoConfeccionadoInventarioMaterial { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
