//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvertarioMateriales
    {
        public InvertarioMateriales()
        {
            this.SalidaMateriales = new HashSet<SalidaMateriales>();
            this.ProductoConfeccionadoInventarioMaterial = new HashSet<ProductoConfeccionadoInventarioMaterial>();
        }
    
        public int Id { get; set; }
        public int MateriaPrimaId { get; set; }
        [DataType(DataType.Currency, ErrorMessage = "Debe ser en formato de moneda")]
        [Required(ErrorMessage = "{0} es obligatorio")]
        [RegularExpression(@"\d*.\d{2}", ErrorMessageResourceName = "DecimalInvalidMessage", ErrorMessageResourceType = typeof(Resources.ResourceGlobal))]
        public decimal Precio { get; set; }

        [Required(ErrorMessage = "{0} es obligatorio")]
        [RegularExpression(@"\d*.\d{2}", ErrorMessageResourceName = "DecimalInvalidMessage", ErrorMessageResourceType = typeof(Resources.ResourceGlobal))]
        public decimal Existencia { get; set; }

        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }

        public int ColorId { get; set; }
    
        public virtual Color Color { get; set; }

        [Display(Name = "Materia Prima")]
        public virtual Material Material { get; set; }
        public virtual ICollection<SalidaMateriales> SalidaMateriales { get; set; }
        public virtual ICollection<ProductoConfeccionadoInventarioMaterial> ProductoConfeccionadoInventarioMaterial { get; set; }

        public string Inventario { get { return Material.DescripcionCompleta + " Color: " + Color.DescricionCompleta + " - " + Precio + " (Cant: " + Existencia +  " " + Material.UnidadMedida.Siglas + ")"; } }

        public string InventarioCorto
        {
            get { return Material.DescripcionCompleta + " Color: " + Color.DescricionCompleta + " (" + Precio + ")"; }
        }
    }
}
