//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.CompraMateriales = new HashSet<CompraMateriales>();
            this.InvertarioMateriales = new HashSet<InvertarioMateriales>();
            this.Producto_Material = new HashSet<Producto_Material>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "{0} es obligatorio")]
        [Remote("CheckNombre", "Material", AdditionalFields = "Id", ErrorMessage = "Ya existe esta Materia Prima")]
        public string Nombre { get; set; }

        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        public int UnidadMedidaId { get; set; }
    
        public virtual ICollection<CompraMateriales> CompraMateriales { get; set; }
        public virtual ICollection<InvertarioMateriales> InvertarioMateriales { get; set; }

        [Display(Name = "Unidad de Medida")]
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual ICollection<Producto_Material> Producto_Material { get; set; }

        public string DescripcionCompleta
        {
            get
            {
                var d = Nombre;
                if (Descripcion != null && Descripcion != "")
                {
                    d += " (" + Descripcion + ")";
                }
                return d;
            }
        }
    }
}
