//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocupacion
    {
        public Ocupacion()
        {
            this.Persona_Trabajador = new HashSet<Persona_Trabajador>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "{0} es obligatorio")]
        [Remote("CheckNombre", "Ocupacion", AdditionalFields = "Id", ErrorMessage = "Ya existe esta Ocupación")]
        public string Nombre { get; set; }
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
    
        public virtual ICollection<Persona_Trabajador> Persona_Trabajador { get; set; }
    }
}
