//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona_Proveedor : Persona
    {
        public Persona_Proveedor()
        {
            this.CompraMateriales = new HashSet<CompraMateriales>();
        }

        [Required(ErrorMessage = "{0} es obligatorio")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Debe ser un correo electrónico")]
        [Display(Name = "Correo Electrónico")]
        [Remote("CheckEmail", "Proveedor", AdditionalFields = "Id", ErrorMessage = "Ya existe este Concepto de Costo")]
        public string Email { get; set; }

        public virtual ICollection<CompraMateriales> CompraMateriales { get; set; }
    }
}
