//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Material
    {
        public int ProductoId { get; set; }
        public int MateriaPrimaId { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
