//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoConfeccionadoInventarioMaterial
    {
        public int InvertarioMateriasPrimasId { get; set; }
        public int EntradaProductosId { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual EntradaProductos EntradaProductos { get; set; }
        public virtual InvertarioMateriales InvertarioMateriales { get; set; }
    }
}
