//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.EntradaProductos = new HashSet<EntradaProductos>();
            this.InvertarioProductos = new HashSet<InvertarioProductos>();
            this.Producto_Material = new HashSet<Producto_Material>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "{0} es obligatorio")]
        [Remote("CheckNombre", "Producto", AdditionalFields = "Id", ErrorMessage = "Ya existe este Producto")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "{0} es obligatorio")]
        public string Modelo { get; set; }
        [Required(ErrorMessage = "{0} es obligatorio")]
        public int Talla { get; set; }

        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
    
        public virtual ICollection<EntradaProductos> EntradaProductos { get; set; }
        public virtual ICollection<InvertarioProductos> InvertarioProductos { get; set; }
        public virtual ICollection<Producto_Material> Producto_Material { get; set; }

        public string DescripcionCompleta
        {
            get
            {
                var d = Nombre + " - Modelo: " + Modelo + " - Talla: " + (Tallas)Talla;
                if (Descripcion != null && Descripcion != "")
                {
                    d += " (" + Descripcion + ")";
                }
                return d;
            }
        }

        public string TallaToString
        {
            get
            {
                switch (Talla)
                {
                    case 1:
                        return "Pequeño";
                    case 2:
                        return "Medio";
                    case 3:
                        return "Grande";
                    case 4:
                        return "ExtraGrande";
                }
                return "INEXISTENTE";
            }
        }
    }
}
