//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PVRA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PvraDataEntities : DbContext
    {
        public PvraDataEntities()
            : base("name=PvraDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaTrabajo> AreaTrabajo { get; set; }
        public virtual DbSet<CompraMateriales> CompraMateriales { get; set; }
        public virtual DbSet<ConceptoGasto> ConceptoGasto { get; set; }
        public virtual DbSet<EntradaProductos> EntradaProductos { get; set; }
        public virtual DbSet<InvertarioMateriales> InvertarioMateriasPrimas { get; set; }
        public virtual DbSet<InvertarioProductos> InvertarioProductos { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<OtrosGastos> OtrosGastos { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Producto_Material> MateriasPrimasPorProducto { get; set; }
        public virtual DbSet<Salario> Salario { get; set; }
        public virtual DbSet<SalidaMateriales> SalidaMateriales { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedida { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<ConceptoCosto> ConceptoCosto { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Ocupacion> Ocupacion { get; set; }
        public virtual DbSet<ProductoConfeccionadoInventarioMaterial> MateriasPrimasUsadas { get; set; }

        public virtual DbSet<Persona_Trabajador> Trabajadores { get; set; }
        public virtual DbSet<Persona_Proveedor> Proveedores { get; set; }
        public virtual DbSet<Salario_CostoProduccion> CostoProducciones { get; set; }
    }
}
