//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salario
    {
        public int Id { get; set; }
        [DataType(DataType.Date, ErrorMessage = "{0} debe ser una fecha")]
        [Required(ErrorMessage = "{0} es obligatorio")]
        public System.DateTime Fecha { get; set; }
        [DataType(DataType.Currency, ErrorMessage = "Debe ser en formato de moneda")]
        [Required(ErrorMessage = "{0} es obligatorio")]
        //[RegularExpression(@"\d*.\d{2}", ErrorMessageResourceName = "DecimalInvalidMessage", ErrorMessageResourceType = typeof(Resources.ResourceGlobal))]
        public decimal Importe { get; set; }
        public int TrabajadorPersonaId { get; set; }
    
        [Display(Name = "Trabajador")]
        public virtual Persona_Trabajador Persona_Trabajador { get; set; }
    }
}
