//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVRA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salario_CostoProduccion : Salario
    {
        public int ConceptoCostoId { get; set; }
        public Nullable<int> EntradaProductosId { get; set; }
    
        public virtual ConceptoCosto ConceptoCosto { get; set; }
        public virtual EntradaProductos EntradaProductos { get; set; }
    }
}
